### ISSUE TITLE
Create a dotcom-core-branding package

### ISSUE THREAD

**Issue by pixelandpage** [Financial-Times/dotcom-page-kit#494]
Page Kit aims to surface its contents to the top level such that the list of packages can be read as a table of contents for the project. 

To meet this goal, our core-branding, including our choices of fonts and colours, should be defined in a separate package and imported by the packages which require them.

**Comment by i-like-robots** [comment]
From discussing this multiple times I think the main "win" from this work would be if it could fix the problems outlined in #763 by centralising the font loading setup into a single place.

**Comment by i-like-robots** [comment]
My current thinking is that a "Core Styles" or "Baseline Styles" package might make sense and also enable us to pull the `n-ui-foundations` package under Page Kit.
