### ISSUE TITLE
Page Kit as a Webpack configuration builder

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/dotcom-page-kit#528]
It has become apparent that the current Page Kit CLI is too complex for our needs and is leading to some confusion about the scope of the project. Because Page Kit provides its own CLI tool it is also worrying users that we are replacing one esoteric system with another.

At its core the current Page Kit CLI enables a complex Webpack configuration to be composed from multiple separate packages. It also makes accessing and modifying specific parts of the configuration simpler and more robust.

However, as discussed in #133 I would like to make it possible to use Webpack's own CLI like this:

```js
// webpack.config.js
module.exports = pageKit(options);
```

Taking this one step further... this would mitigate the need to maintain, document, and support an additional tool. I would also hope that by focusing on the configuration aspect it removes any worries about straying too far from "standard" tools.

This issue supersedes #58 and #123 and #133.

**Comment by i-like-robots** [comment]
Coming back to this as something to think about in the new year:

> Modify any part of the Webpack configuration in a discoverable way

Apart from specifying entry points and adding plugins I'm not sure this use case has come up. If we drop this requirement then that may enable us to deliver a regular Webpack configuration without any ceremony 🤔

**Comment by quarterto** [comment]
there've been a couple of times where we've had to do this in a limited way (mostly adding or configuring plugins or loaders)

**Comment by i-like-robots** [comment]
GitHub recommended this project to me to follow: https://github.com/namics/webpack-config-plugins

I thought it was interesting that each plugin used Webpack's own plugin architecture:

```js
// webpack.config.js
const ScssConfigWebpackPlugin = require('scss-config-webpack-plugin');

module.exports = {
    plugins: [
        new ScssConfigWebpackPlugin()
    ]
};
```

Custom configuration is straightforward to add and options can also be passed to the plugin constructor.

Perhaps this pattern would also suit our needs?

**Comment by apaleslimghost** [comment]
i think we could wholesale replace our CLI and plugins with that, plus maybe some of our own
