### ISSUE TITLE
Performance tracking for FT.com apps

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/dotcom-page-kit#616]
- using Speedcurve. mostly interested in Time To Interactive
- test the Big 3 apps (front page, stream page, article)
- test with ads and GTM on, ads on & GTM off, ads & GTM off
- investigate testing a user journey

prior art: https://github.com/Financial-Times/next-go-faster
see also: #560

**Comment by i-like-robots** [comment]
Closing this as I believe we have completed this task.
