### ISSUE TITLE
Real User Monitoring (RUM): User-centric Performance Metrics

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/dotcom-page-kit#685]
**The Problem**

We can use performance measurement tools to glean some understanding of how our web pages perform, but these all run in test environments. How do our pages _really_ perform for _real_ users? 

Field notes: https://docs.google.com/document/d/1m6tIfDQyz_2x_hGRhTBC8ZXgyrXSjjZ_S_nZLmFkJnI/

**Comment by i-like-robots** [comment]
Closing this as this feature has been implemented as part of the `n-tracking` component: https://github.com/Financial-Times/n-tracking/pull/27
