### ISSUE TITLE
Ensure smoke tests run by apps check assets load correctly

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/dotcom-page-kit#738]
Currently apps running Page Kit cannot load their assets when run in production mode on staging. This is due to apps being configured to use a path which only available when accessed via the CDN.

To remedy this we can configure the asset loader with an absolute URL instead (requires #737):

```diff
assetsMiddleware.init({
	hostStaticAssets: !isProduction,
-	publicPath: isProduction ? '/__assets/hashed/page-kit' : '/__dev/assets/stream-page'
+	publicPath: isProduction ? 'https://www.ft.com/__assets/hashed/page-kit' : '/__dev/assets/stream-page'
}),
```

We should update the smoke tests in each application to check that assets have been loaded or initialised correctly.

**Comment by i-like-robots** [comment]
This is the smoke test I've come up with from a quick hack:

```ja
	{
		timeout: 15000,
		urls: {
			'/stream/82645c31-4426-4ef5-99c9-9df6e0940c00?page-kit-loaded': {
				status: 200,
				waitUntil: 'load',
				elements: {
					// Ensure global JS is initialised
					'[data-o-header--js]': true,
					'[data-o-footer--js]': true,
					// Ensure global styles are loaded
					'.n-ui-hide-enhanced': 0
				}
			}
		}
	},
```

**Comment by pixelandpage** [comment]
> '.n-ui-hide-enhanced': 0

I don't quite understand how this indicates that the global styles have loaded. Is there logic somewhere to remove the class on load?

**Comment by andygout** [comment]
Also wondering if there is a way we can ensure that CSS is loaded as well as the JS. Probably no indicator in the DOM that we can hook into… 🤔

**Comment by i-like-robots** [comment]
There's an important detail missing here, which is that `n-test` checks for _visible_ elements, not whether the element is present in the DOM or not:

https://github.com/Financial-Times/n-test/blob/master/lib/checks/elements.js#L17-L30

My idea is that checking for elements which should be hidden are actually hidden should tell us that styles have loaded.

There is also a network requests check, but insofar as I can tell this only checks a request was triggered and not whether it was successful or not.

**Comment by pixelandpage** [comment]
This looks good to me. Thanks for updating the inline comments 🙂

**Comment by i-like-robots** [comment]
I've implemented this in https://github.com/Financial-Times/next-stream-page/pull/2340

I propose we roll something similar out to all apps as part of the upgrade to Page Kit v0.6.0.

**Comment by i-like-robots** [comment]
I can confirm that the following smoke test is flaky. I have run it multiple times against the stream page app running without access to any assets and it _can pass_. 

```js
	{
		timeout: 15000,
		urls: {
			'/stream/82645c31-4426-4ef5-99c9-9df6e0940c00': {
				headers: {
					'FT-Flags': 'ads:off'
				},
				status: 200,
				waitUntil: 'load',
				browsers: true,
				elements: {
					'html.enhanced.js': true
				}
			},
		},
	}
```

Although the `.enhanced` class name is removed when JS loading fails this seems to not always occur before the window `load` event, at least when loading the page in a headless browser. I cannot recreate this in my own browser, the fallback is _always_ triggered before the `load` event.

<img width="1440" alt="Screenshot 2020-01-28 at 09 14 54" src="https://user-images.githubusercontent.com/271645/73250628-1d9afc00-41af-11ea-9d0e-2e3968bd14af.png">

The updated test does is more consistent and does fail as expected when there are no assets loading:

<img width="865" alt="Screenshot 2020-01-28 at 09 13 32" src="https://user-images.githubusercontent.com/271645/73250811-8bdfbe80-41af-11ea-9c1d-d2ca4bfcb97b.png">

However, the `pageErrors` option may be of limited use.

**Comment by andygout** [comment]
#### Apps with smoke tests modified:
- [ ] `next-static`
- [ ] `next-search-page`
- [ ] `next-video-page`
- [ ] `next-errors`
- [ ] `next-epaper`
- [ ] `next-tour-page`
- [ ] `next-graphics-page`
- [ ] `next-profile`
- [ ] `next-syn-list`
- [ ] `next-product`
- [ ] `next-b2b-prospect`
- [x] `next-retention`
- [ ] `next-subscribe`
- [ ] `next-stream-page`
- [ ] `next-front-page`
- [ ] `next-myft-page`
- [ ] `next-article`
- [ ] `next-control centre`

**Comment by andygout** [comment]
All finished!
