### ISSUE TITLE
Upgrade apps to Page Kit v0.6

### ISSUE THREAD

**Issue by andygout** [Financial-Times/dotcom-page-kit#754]
https://github.com/Financial-Times/dotcom-page-kit/wiki/Upgrading-from-0.5.x-to-0.6.x

- `next-static`
  - [x] Node v12: https://github.com/Financial-Times/next-static/pull/129
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-static/pull/133
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-static/pull/132
- `next-search-page`
  - [x] Node v12: https://github.com/Financial-Times/next-search-page/pull/360
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-search-page/commit/e225f2842a4bf192760de8a1970ad648053fafef
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-search-page/pull/360
- `next-video-page`
  - [x] Node v12: https://github.com/Financial-Times/next-video-page/pull/300
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-video-page/pull/304
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-video-page/pull/302
- `next-errors`
  - [x] Node v12: https://github.com/Financial-Times/next-errors/pull/191
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-errors/pull/194
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-errors/pull/193
- `next-epaper`
  - [x] Node v12: https://github.com/Financial-Times/next-epaper/pull/89
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-epaper/pull/91
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-epaper/pull/90
- `next-tour-page`
  - [x] Node v12: https://github.com/Financial-Times/next-tour-page/pull/256
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-tour-page/pull/259
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-tour-page/pull/258
- `next-graphics-page`
  - [x] Node v12: https://github.com/Financial-Times/next-graphics-page/pull/244
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-graphics-page/pull/246
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-graphics-page/pull/245
- `next-profile`
  - [x] Node v12: https://github.com/Financial-Times/next-profile/pull/272
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-profile/pull/280
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-profile/pull/277
- `next-syn-list`
  - [x] Node v12: https://github.com/Financial-Times/next-syn-list/pull/93
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-syn-list/pull/96
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-syn-list/pull/94
- `next-product`
  - [x] Node v12: https://github.com/Financial-Times/next-product/pull/859
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-product/pull/864
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-product/pull/862
- `next-b2b-prospect`
  - [x] Node v12: https://github.com/Financial-Times/next-b2b-prospect/pull/147
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-b2b-prospect/pull/149
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-b2b-prospect/pull/148
- `next-retention`
  - [x] Node v12: https://github.com/Financial-Times/next-retention/pull/354
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-retention/pull/369
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-retention/pull/354
- `next-subscribe`
  - [x] Node v12: https://github.com/Financial-Times/next-subscribe/pull/967
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-subscribe/pull/974
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-subscribe/pull/972
- `next-stream-page`
  - [x] Node v12: https://github.com/Financial-Times/next-stream-page/pull/2352
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-stream-page/pull/2354
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-stream-page/pull/2354
- `next-front-page`
  - [x] Node v12: https://github.com/Financial-Times/next-front-page/pull/2258
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-front-page/pull/2265
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-front-page/pull/2257
- `next-myft-page`
  - [x] Node v12: https://github.com/Financial-Times/next-myft-page/pull/2243
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-myft-page/pull/2243
  - [x] Page Kit v0.6:
- `next-article`
  - [x] Node v12: https://github.com/Financial-Times/next-article/pull/3678
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-article/pull/3682
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-article/pull/3681
- `next-control-centre`
  - [x] Node v12: https://github.com/Financial-Times/next-control-centre/pull/126
  - [x] Set Node version to 12.x: https://github.com/Financial-Times/next-control-centre/pull/126
  - [x] Page Kit v0.6: https://github.com/Financial-Times/next-control-centre/pull/124

**Comment by i-like-robots** [comment]
The progress spreadsheet should also be updated https://docs.google.com/spreadsheets/d/1wOp6suvluEVmD3v8GEmP5jXRzoSpUazSN4G5HHdpQY0/edit?ts=5e173179#gid=0
