### ISSUE TITLE
Create a dotcom-ui-client-embed package for sharing data between the server and the client

### ISSUE THREAD

**Issue by pixelandpage** [Financial-Times/dotcom-page-kit#799]
Currently we have no defined method for apps to share data between the client and the server. [Some apps](https://github.com/Financial-Times/dotcom-page-kit/pull/761) have resorted to updating the `appContext` object as a way around this but we want to discourage this practice and `v0.7.0` of Page Kit introduced errors when modifying `appContext` to prevent this behaviour.

Proposal:

- Create a new dotcom-ui-client-embed package containing all of the logic required to pass data from the server to the client without modifying `appContext`.
- Refactor dotcom-middleware-app-context and dotcom-middleware-flags to use this new package rather than duplicating the same functionality in multiple places.
- Document a process for other apps to make use of the new package to pass custom properties from the client to the server.
- Incorporate this functionality into an example app.

**Comment by andygout** [comment]
Case study: `next-video-page`, which currently adds this to `appContext`:

```
{
	permutiveContext: {
		publicId: process.env.PERMUTIVE_PUBLIC_ID,
		publicApikey: process.env.PERMUTIVE_PUBLIC_API_KEY
	}
}
```

**Comment by nickcolley** [comment]
One thought... If someone fails the appContext schema validation we could consider pointing them to the documentation for this...

**Comment by pixelandpage** [comment]
Yes, I think so 👍 At the moment I believe we serve a Typescript error but we could definitely do better than this! 

We actually have a design decisions doc about appContext which has become out-of-date; if we update that as part of this work then it might be a good resource to point to in the event of a validation error https://github.com/Financial-Times/dotcom-page-kit/blob/master/docs/design-decisions/app-context.md
