### ISSUE TITLE
Check if label property exists before run ToLowerCase

### ISSUE THREAD

**Issue by juanSanchezAlcala** [Financial-Times/dotcom-page-kit#969]
https://github.com/Financial-Times/dotcom-page-kit/blob/e4a678f2a5c168aec2cbdf2750f32751500cffe9/packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx#L125

label property could be null and therefore in those cases javascript will throw an error since we are not checking if it exist. I suggest set `props?.label?.toLowerCase` instead

**Comment by ivomurrell** [comment]
The `label` property is typed as always existing on the `props` object in [dotcom-types-navigation](https://github.com/Financial-Times/dotcom-page-kit/blob/e4a678f2a5c168aec2cbdf2750f32751500cffe9/packages/dotcom-types-navigation/index.d.ts#L48), and the `props` argument isn't optional for that function, so we _shouldn't_ need to defensively check whether `props` or `label` are nullable. That's assuming the TypeScript type assertions are correct though.

Do you have an example where the `label` property was null? We could either update the `TNavMenuItem` type to declare `label` as nullable or fix the code which is assuming an object is of type `TNavMenuItem` when it isn't.

**Comment by juanSanchezAlcala** [comment]
Yes you are right, i was confused due some test had failed and I've misread the type of the props , I was thinking about TNavMenu instead TNavMenuItem. Sorry for the confusion
